name: 'Deploy Akash'
description: 'Deploy akash to a provider'
inputs:
  github_token:
    description: 'Github token'
    required: true
  seed:
    description: 'Deploy wallet seed'
    required: true
  password:
    description: 'Password to encrypt the wallet'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
env:

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash