name: Restore the state

inputs:
  PROJECT_PATH:
    description: 'Path to the project'
    required: true
    type: string

runs:
  using: "composite"

  steps:
  - name: Restore the state
    id: restore-state
    continue-on-error: true
    shell: bash
    run: |
      if [[ -f ${{ inputs.PROJECT_PATH }}/.akash/DSEQ && -f ${{ inputs.PROJECT_PATH }}/.akash/PROVIDER ]]; then
        AKASH_DSEQ=$(cat ${{ inputs.PROJECT_PATH }}/.akash/DSEQ)
        AKASH_PROVIDER=$(cat ${{ inputs.PROJECT_PATH }}/.akash/PROVIDER)
      fi
      test ! -z "$AKASH_DSEQ"
      test ! -z "$AKASH_PROVIDER"
      echo "Expecting $AKASH_DSEQ/$AKASH_GSEQ/$AKASH_OSEQ deployment on $AKASH_PROVIDER provider."
      echo "Going to verify whether it is alive."
      echo "AKASH_DSEQ=$AKASH_DSEQ" >> $GITHUB_ENV
      echo "AKASH_PROVIDER=$AKASH_PROVIDER" >> $GITHUB_ENV
