name: Destroy me
#description: Close a single deployment based on the state (.akash/{DSEQ,PROVIDER})

on:
  workflow_call:
    inputs:
      PROJECT_PATH:
        description: 'Path for the project to deploy'
        required: false
        default: '.'
        type: string
      project_name:
        description: 'Project name (will be used as prefix for cache keys)'
        required: false
        default: 'app'
        type: string
    secrets:
      SEED:
        description: 'Seed phrase for the wallet'
        required: true
      PASSWORD:
        description: 'Password to decrypt the wallet'
        required: true
      ghcr-token:
        description: 'GITHUB_TOKEN'
        required: true

env:
  ORG: akash-network
  REPO: provider
  CLIENT: provider-services
  CLIENT_VERSION: 0.1.0
  ARCH: amd64
  # Akash Network
  NET: mainnet
  #BLOCK_TIME: 6s
  BLOCK_TIME: 1s
  # Quit if chain is running 30 seconds behind
  CHAIN_LATENCY: 30
  # Akash Client parameters
  AKASH_KEYRING_BACKEND: file
  AKASH_BROADCAST_MODE: block
  #AKASH_BROADCAST_MODE: async
  AKASH_YES: 1
  AKASH_GAS_PRICES: 0.025uakt
  AKASH_GAS: auto
  AKASH_GAS_ADJUSTMENT: 1.5
  AKASH_HOME: /home/runner/.akash
  AKASH_FROM: default
  AKASH_OUTPUT: json
  # Minimum balance on the wallet in AKT
  MIN_BALANCE: 10
  AKASH_GSEQ: 1
  AKASH_OSEQ: 1
  SDL: deploy.yaml
  #PROVIDER: akash18ga02jzaq8cw52anyhzkwta5wygufgu6zsz6xc


jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Call Initialize Akash client
      uses: TedcryptoOrg/akash-deploy-action/.github/actions/init-akash@main
      with:
        seed: ${{ secrets.SEED }}
        password: ${{ secrets.PASSWORD }}
        project_name: ${{ inputs.project_name }}

    # Restore .akash/{DSEQ,PROVIDER} state
    - name: Call Restore state
      id: call-restore-state
      uses: TedcryptoOrg/akash-deploy-action/.github/actions/restore-state@main
      with:
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}

    - name: Call Get deployment status
      id: call-get-deployment-status
      if: |
        steps.call-restore-state.outcome == 'success' &&
        ( env.AKASH_DSEQ != '' && env.AKASH_PROVIDER != '' )
      uses: TedcryptoOrg/akash-deploy-action/.github/actions/get-deployment-status@main

    - name: Call Close state deployment
      uses: TedcryptoOrg/akash-deploy-action/.github/actions/close-state-deployment@main
      if: steps.call-get-deployment-status.outputs.is-deployment-active == 'true'
      with:
        password: ${{ secrets.PASSWORD }}
        github_token: ${{ secrets.ghcr-token }}
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
